Repository fdorg/flashdevelop, pull requests merged in 2020-09, with the labels that each got.

#3043 [HaxeContext] Fix NPE. fixes #3038
  External/Plugins/HaXeContext/PluginMain.cs
Labels: bug, haxe

#3052 [Haxe][CompletionList] Fixed: Popup completion list replaced with different popup completion list. fixes #2177
  External/Plugins/ASCompletion/Completion/ASComplete.cs
  PluginCore/PluginCore/Controls/CompletionList.cs
Labels: enhancement, haxe

#3053 [ASClassWizard] Fixed: Bug on implementation 2 interfaces. fixes #2949
  External/Plugins/ASClassWizard/PluginMain.cs
  External/Plugins/ASCompletion/Context/ASContext.cs
Labels: bug

#3058 [UnitTests] Bump NETCore.Platforms to 3.1.3
  Tests/External/Plugins/AS3Context.Tests/packages.config
  Tests/External/Plugins/ASCompletion.Tests/packages.config
  Tests/External/Plugins/CodeRefactor.Tests/packages.config
  Tests/External/Plugins/HaxeContext.Tests/packages.config
  Tests/External/Plugins/ProjectManager.Test/packages.config
  Tests/PluginCore/PluginCore.Tests/packages.config
Labels: UnitTests

#3064 Fixes #3062
  External/Plugins/FlashDebugger/Debugger/BreakPointManager.cs
Labels: regression

#3066 Fixed: [Regression] FD editor adds wrong import. fixes #3063
  External/Plugins/ASCompletion/Completion/ASComplete.cs
Labels: bug, haxe

#3067 [UnitTests] Added test for #3048. closes #3049
  External/Plugins/ASCompletion/Completion/ASComplete.cs
  Tests/External/Plugins/HaxeContext.Tests/Completion/Haxe3/CodeCompleteTests.cs
  Tests/External/Plugins/HaxeContext.Tests/HaxeContext.Tests.csproj
  Tests/External/Plugins/HaxeContext.Tests/Test Files/completion/AfterOnCharAndReplaceText_issue3048_1.hx
  Tests/External/Plugins/HaxeContext.Tests/Test Files/completion/AfterOnCharAndReplaceText_issue3048_2.hx
  Tests/External/Plugins/HaxeContext.Tests/Test Files/completion/AfterOnCharAndReplaceText_issue3048_3.hx
  Tests/External/Plugins/HaxeContext.Tests/Test Files/completion/BeforeOnCharAndReplaceText_issue3048_1.hx
  Tests/External/Plugins/HaxeContext.Tests/Test Files/completion/BeforeOnCharAndReplaceText_issue3048_2.hx
  Tests/External/Plugins/HaxeContext.Tests/Test Files/completion/BeforeOnCharAndReplaceText_issue3048_3.hx
Labels: UnitTests, coderefactor

#3068 [UnitTests] 2400 tests
  External/Plugins/ASCompletion/Completion/ASGenerator.cs
  Tests/External/Plugins/ASCompletion.Tests/Completion/ASGeneratorTests.cs
  Tests/External/Plugins/ASCompletion.Tests/TestUtils/ContextExtensions.cs
  Tests/External/Plugins/HaxeContext.Tests/Completion/Haxe3/CodeCompleteTests.cs
  Tests/External/Plugins/HaxeContext.Tests/Generators/Haxe3/CodeGeneratorTests.cs
  Tests/External/Plugins/HaxeContext.Tests/Generators/Haxe3/CodeGeneratorTests2.cs
  Tests/External/Plugins/HaxeContext.Tests/Generators/Haxe3/DocumentationGeneratorTests.cs
  Tests/External/Plugins/HaxeContext.Tests/Generators/Haxe4/CodeGeneratorTests.cs
  Tests/External/Plugins/HaxeContext.Tests/HaxeContext.Tests.csproj
  Tests/External/Plugins/HaxeContext.Tests/Test Files/generators/code/AfterContextualGeneratorTests_GenerateFunction_5.hx
Labels: UnitTests
